### ISSUE TITLE
Can't switch teams anymore if mod active

### ISSUE THREAD

**Issue by Joe91** [FlashHit/BetterIngameAdmin#37]
Maybe just a setting, but I havend foud it jet...
If i try to switch the team it just sais, that this is disabled.

**Comment by FlashHit** [comment]
Yes this is intended. So the Assist function can work without problems. 
However, the next update will include Modsettings that lets you manage things like this.
For now, you can remove the Shared folder of the mod to activate it again, but this might break the Assist function.

**Comment by Joe91** [comment]
thank you very much! Realy geat work!!

**Comment by FlashHit** [comment]
Added a setting in `0.1.0`
If you disable the assist function in the mod settings you can use the vanilla team switching again (applied on the next loading screen)
