### ISSUE TITLE
Not getting ownership rights. | Attempt to index a nill vallue. ext/Client/__init__.lua (Line 1141)

### ISSUE THREAD

**Issue by lywit** [FlashHit/BetterIngameAdmin#38]
[betteringameadmin-main] Error: [string "__init__.lua"]:1141: attempt to index a nil value (local 'localPlayer')

This happens in a function that is used to set the Owner's rights. As the owner of my server, I don't get admin controlls anymore.
I'm on the latest version, downloaded on 30-12-2020.

**Comment by FlashHit** [comment]
Will be fixed in the next update.

**Comment by FlashHit** [comment]
Fixed in `0.1.0`.
