### ISSUE TITLE
[FEATURE] Add support for SP and Coop maps - Currently they show up as undefined

### ISSUE THREAD

**Issue by keku645** [FlashHit/BetterIngameAdmin#59]
![image](https://user-images.githubusercontent.com/36018654/132499798-67480f5b-b725-41e6-906e-124b6443c293.png)

Whole list of maps.

Coop_002         -    Hit and Run
Coop_003         -    Drop 'Em Like Liquid
Coop_006         -    Fire from the Sky
Coop_007         -    Operation Exodus
Coop_009         -    Exfiltration
Coop_010         -    The Eleventh Hour
SP_Bank          -    Operation Guillotine
SP_Earthquake    -    Operation Swordbreaker
SP_Earthquake2   -    Uprising
SP_Finale        -    The Great Destroyer
SP_Interrogation -    Intro
SP_Jet           -    Going Hunting
SP_New_York      -    Semper Fidelis
SP_Paris         -    Comrades
SP_Sniper        -    Night Shift
SP_Tank          -    Thunder Run
SP_Tank_b        -    Fear No Evil
SP_Valley        -    Rock and a Hard Place
SP_Villa         -    Kaffarov

**Comment by FlashHit** [comment]
implemented in 8a7bd46
`version 0.1.7`
